os: linux
language: android
dist: xenial
env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3
  - ANDROID_ABI=armeabi-v7a
android:
  components:
    - tools
    - platform-tools-28.0.2
    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

jdk: oraclejdk8
sudo: required
addons:
  apt:
    sources:
      - sourceline: deb https://dl.yarnpkg.com/debian/ stable main
        key_url: https://dl.yarnpkg.com/debian/pubkey.gpg
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default
before_script:
- wget https://services.gradle.org/distributions/gradle-5.2.1-bin.zip
- unzip -qq gradle-5.2.1-bin.zip
- export GRADLE_HOME=$PWD/gradle-5.2.1
- export PATH=$GRADLE_HOME/bin:$PATH
- git clone https://github.com/flutter/flutter.git -b dev --depth 1
- export PATH=./flutter/bin:$PATH
script:
- "./flutter/bin/flutter -v build apk"
cache:
  directories:
  - "$HOME/.pub-cache"
deploy:
  provider: releases
  api_key:
    secure: Pf/FD9fwLip11OH4LTp5+i3QBFLffcTFqF9sVrDJIjWi5fiR3Q2U05oWwMwto2QMMSflnEIsbBupXqnG36aFJmk+IrJ2cZXUXeUgo9yNqu/ZmVq7/hj0vLQ916ZaFHNefT1REkqXgSnxa6BF1yttN3T6cC2W8irHDhWUy8C4DFNMHcrQbu8kF30PeqJi8vahDk6OWVMjUzc8HZbpo/lzwfqLMxAY7Y9RlbBYzUnLz+yAs99ZOuZKS1K71f/Ti/v9qO5hhlSqj9pg1cEfyDc05+uh4SOEUfRCikjBN2dO5wqIykWWdEv64I43siXsEh69Sc/bxSHQeAgt3bPAJC5pJWX5S5mQjEq5M3bv6lLVH/sY5L8T2QijzcvQ1hG5Tc10jcV5oK91D+yYKSjaJZYjvW2T27eJoEAXT5TZF4MbAMBqCpI+iyBWWeHMLJaFMe7rODTJzvnQm47RAWI1VQY/M37vpob0IQiTNALhJnMREMd/MHazNRJcZeeuI1nUqlKWoXyyLoCcF96uH8BifGCKmwO2qaFT6vps1xlZcOmZblgYvckaEVTLxpURh3EIPWL9zaVubYo3nOOyB5/JrOlseYPoG4Uu7AsWImLJ/YAqBmT27PmGcFMl2YcwYT2tl0P/LPr7LoP0fklXZ5ui01IoMnZ+QKCMnwr8vSjkjg3u0U8=
  file: build/app/outputs/apk/release/app-release.apk
  skip_cleanup: true
  on:
    tags: true
before_install:
- gem install fir-cli
- yes | sdkmanager "platforms;android-27"
- yes | sdkmanager "platforms;android-28"
- yes | sdkmanager "build-tools;28.0.3"
- openssl aes-256-cbc -K $encrypted_07a3a6eaa6eb_key -iv $encrypted_07a3a6eaa6eb_iv
  -in key.jks.enc -out key.jks -d
after_deploy:
  - fir p build/app/outputs/apk/release/app-release.apk -T $FIR_TOKEN -c "`git cat-file tag $TRAVIS_TAG`"
